FROM golang:1.26-alpine AS builder

WORKDIR /src

COPY app.go .

RUN CGO_ENABLED=0 GOOS=linux \
    go build -ldflags="-s -w" -o /app app.go

FROM gcr.io/distroless/static-debian12:nonroot

COPY --from=builder \
     --chown=65532:65532 \
     /app /app

USER 65532:65532

ENTRYPOINT ["/app"]
