---
apiVersion: v1
kind: Pod
metadata:
  name: kubectl-client
spec:
  serviceAccountName: operator
  containers:
    - name: kubectl-container
      image: alpine/kubectl:1.35.4
      command: ["sleep", "86400"]
