---
apiVersion: v1
kind: Pod
metadata:
  name: kubectl-client
spec:
  serviceAccountName: operator
  automountServiceAccountToken: true
  containers:
    - name: kubectl-container
      image: alpine/kubectl:1.34.2
      command: ["sleep", "86400"]
