---
apiVersion: v1
kind: Pod
metadata:
  name: app-private
  namespace: supply-chain
spec:
  imagePullSecrets:
  - name: registry-credentials
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: app
    image: registry:5000/app-golang:v1
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
