---
apiVersion: v1
kind: Pod
metadata:
  name: pod-restricted
  namespace: pss-restricted
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 3000
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: pod-restricted
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
