---
apiVersion: v1
kind: Pod
metadata:
  name: pod-privileged
  namespace: pss-baseline
spec:
  containers:
  - name: pod-privileged
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      privileged: true
